import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
      <nav>
        <h1>MedFlex Tech</h1>
        <button>Log Out</button>
      </nav>
        {children}
        </body>
    </html>
  );
}
